### ISSUE TITLE
How to decide to configure SFE or Flow Offload

### ISSUE THREAD

**Issue by demorphica** [gwlim/openwrt-sfe-flowoffload#5]
how do we make the decision on whether to enable SFE vs. Flow Offload?
Are there any considerations which would help decide?
referencing your comment https://github.com/gwlim/openwrt-sfe-flowoffload/issues/1#issuecomment-444484583 in #1

**Comment by gwlim** [comment]
SFE and Flow Offload are functionally equivalent.
They do the same thing.
You will not get X2 the performance if you enable both at the same time.
I included both because some people like SFE while others like Flow Offload it is a new feature that LEDE 17 does not have made by Openwrt developers.
It is up to you to decide which you want.
However between SFE and Flow Offload I benchmarked, one is 200Mbps faster on TP-Link WR1043NDv1. As for which I will let you guess. 😁
To enable SFE start the Service in SYSTEM -> STARTUP
To enable Flow Offload check enable Flow Offload in NETWORK -> Firewall
