### ISSUE TITLE
USB storage

### ISSUE THREAD

**Issue by Zsolteeca** [gwlim/openwrt-sfe-flowoffload#77]
How can I use the usb storage via the router and Fastpath lede?

Need the following information:

file system to format
how can I reach the storage with command lines

Thanks for answers!

**Comment by kolomparrudi** [comment]
Hi Zsolteeca,

You have to install the needed kernel modules and utilities:
kernal modules: kmod-fs-ext4 kmod-usb-storage kmod-usb-ohci kmod-usb-uhci
utils: block-mount e2fsprogs fdisk

For kernel modules unpack the kmod-package.tar.gz to /tmp and use opkg install /tmp/filename
Don't use openwrt repository for kmod install, because you'll get version mismatch.
